[versions]
kotlin_version = "1.8.20"
koin_ktor = "3.4.3"

[libraries]
server_core = { module = "io.ktor:ktor-server-core-jvm" }
server_sessions = { module = "io.ktor:ktor-server-sessions-jvm" }
server_calllogging = { module = "io.ktor:ktor-server-call-logging-jvm" }
server_contentnegotiation = { module = "io.ktor:ktor-server-content-negotiation-jvm" }
server_kotlinxserialization = { module = "io.ktor:ktor-serialization-kotlinx-json-jvm" }
server_websockets = { module = "io.ktor:ktor-server-websockets-jvm" }
server_netty = { module = "io.ktor:ktor-server-netty-jvm" }
#koin-dependencies
koin_ktor = { module = "io.insert-koin:koin-ktor", version.ref = "koin_ktor" }
koin_logger = { module = "io.insert-koin:koin-logger-slf4j", version.ref = "koin_ktor" }
#test-dependencies
server_test = { module = "io.ktor:ktor-server-tests-jvm" }
kotlin_test = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin_version" }

